image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- git
- hugo
- hut
tasks:
- build: |
    cd do-not-track.dev
    hugo
- package: |
    cd do-not-track.dev/public
    tar -cvz . > ~/site.tar.gz
- upload: |
    hut pages publish -d do-not-track.dev site.tar.gz
- mirror-to-github:
    cd do-not-track.dev
    git remote add github git@github.com:mpldr/do-not-track.git
    git push --force github
